language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.8

sudo: false

services:
  - docker

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

stages:
  - name: test
  - name: publish
    if: tag =~ v\d+\.\d+\.\d+

jobs:
  include:
    - stage: test
      script:
        - sbt ++$TRAVIS_SCALA_VERSION test
    - stage: publish
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - sbt ++$TRAVIS_SCALA_VERSION "docker:publish"
